[workspace]
members = [
    "spider",
    "spider_worker",
    "spider_cli",
    "spider_utils",
    "spider_transformations",
    "spider_chrome",
    "spider_firewall",
    # internal
    "examples",
    "benches"]
resolver = "2"
