[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
spider = { version = "1.5.5", path = "../spider" }
tester = "0.5.0"

[[bench]]
name = "crawl"
path = "crawl.rs"
harness = false